#!/usr/bin/env sh
if [ -z "${2-}" ] || [ "$2" = "message" ]; then
    echo "\n ✒️ Ativando Commitizen para criar mensagem de commit estruturada..."

    sleep 3
    
    # Redireciona stdin para permitir interação com o usuário
    exec < /dev/tty && npx cz --hook || {
        echo "\n 📝 Commitizen cancelado. Usando mensagem padrão do git..."
        sleep 2
        exit 0
    }
fi